### ISSUE TITLE
figma update and mobile view

### ISSUE THREAD

**Issue by KingPanda68** [zuri-training/Auth_Wiki_Team_3#51]
Designing the mobile version [hifi] for the support page

**Comment by Oritsemami** [comment]
Task 1 working on the style guide
https://www.figma.com/file/1nSkujDeKRasc9NBEdbxRD/Team-3_Auth-Wiki-Figma-Board?node-id=74%3A59

Tasks 2,3 and 4
Working on the support page
Working on the Lowfi of the support page
Designing the mobile version [hifi] for the support page
https://www.figma.com/file/1nSkujDeKRasc9NBEdbxRD/Team-3_Auth-Wiki-Figma-Board?node-id=328%3A786

**Comment by KingPanda68** [comment]
Resolved
